#### Build the model to find whether the person will be defaulter for loan or not when income & balanceof the person provided

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Datasets/Default.csv")
data.head()

  default student      balance       income
0      No      No   729.526495  44361.62507
1      No     Yes   817.180407  12106.13470
2      No      No  1073.549164  31767.13895
3      No      No   529.250605  35704.49394
4      No      No   785.655883  38463.49588

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   default  10000 non-null  object
 1   student  10000 non-null  object
 2   balance  10000 non-null  float64
 3   income   10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 312.6+ KB

In [4]:
data.describe()

            balance        income
count  10000.000000  10000.000000
mean     835.374886  33516.981876
std      483.714985  13336.639563
min        0.000000    771.967729
25%      481.731105  21340.462905
50%      823.636973  34552.644800
75%     1166.308387  43807.729275
max     2654.322576  73554.233500

In [5]:
data.shape

(10000, 4)

In [6]:
data['student'].value_counts()

student
No     7056
Yes    2944
Name: count, dtype: int64

In [7]:
data['default'].value_counts()

default
No     9667
Yes     333
Name: count, dtype: int64

In [8]:
data.describe()

            balance        income
count  10000.000000  10000.000000
mean     835.374886  33516.981876
std      483.714985  13336.639563
min        0.000000    771.967729
25%      481.731105  21340.462905
50%      823.636973  34552.644800
75%     1166.308387  43807.729275
max     2654.322576  73554.233500

In [9]:
mean = data['balance'].mean()
std = data['balance'].std()

In [10]:
data[data['balance'] > mean + (3 * std)].count()      # upper bound

default    20
student    20
balance    20
income     20
dtype: int64

In [11]:
data[data['balance'] < mean - (3 * std)].count()      # lowwer bound

default    0
student    0
balance    0
income     0
dtype: int64

In [12]:
data.drop(data[data['balance'] > mean + (3 * std)].index, inplace=True)

In [13]:
data.shape

(9980, 4)

In [14]:
data.drop('student', axis = 1, inplace=True)

In [15]:
data.head()

  default      balance       income
0      No   729.526495  44361.62507
1      No   817.180407  12106.13470
2      No  1073.549164  31767.13895
3      No   529.250605  35704.49394
4      No   785.655883  38463.49588

### We will do scalling after input & output separation

In [16]:
X = data.drop('default', axis=1)
y = data['default']

In [17]:
data.describe()

           balance        income
count  9980.000000   9980.000000
mean    832.247137  33530.953295
std     479.101692  13331.877798
min       0.000000    771.967729
25%     481.127011  21357.458397
50%     821.496224  34562.497710
75%    1164.542737  43810.685280
max    2269.946966  73554.233500

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
ss = StandardScaler()
X_ss = ss.fit_transform(X)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_ss, y, test_size=0.2, random_state = 40)

### Build Model

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
model = KNeighborsClassifier(n_neighbors = 3)

#### Cross Validation

In [24]:
from sklearn.model_selection import cross_validate

In [25]:
result = cross_validate(model, X_train, y_train, cv=5)
result

{'fit_time': array([0.0081234 , 0.00781679, 0.01045704, 0.0062151 , 0.00693393]),
 'score_time': array([0.00664473, 0.00937986, 0.01279044, 0.00610375, 0.00495148]),
 'test_score': array([0.9686913 , 0.95867251, 0.96556043, 0.97244834, 0.96929825])}

In [27]:
print('Validation Score : ', result['test_score'].mean())

Validation Score :  0.9669341638378978

In [29]:
model.fit(X_train, y_train)
from sklearn.metrics import accuracy_score
accuracy_score(y_train, model.predict(X_train))

0.9770791583166333