In [1]:
import pandas as pd

In [3]:
emp = pd.DataFrame({'ID' : [101,102,103,104,105], 'Name' : ['Kiran','Om','Poonam','Anushka','Vikram'],
                    'Dept_ID' : [1, 2, 1, 3, 2]})
emp

    ID     Name  Dept_ID
0  101    Kiran        1
1  102       Om        2
2  103   Poonam        1
3  104  Anushka        3
4  105   Vikram        2

In [4]:
dept = pd.DataFrame({'ID' : [1,2,3,4] , 'DEPT_NAME' : ['Developer','Tester', 'HR', 'Admin']})
dept

   ID  DEPT_NAME
0   1  Developer
1   2     Tester
2   3         HR
3   4      Admin

In [6]:
pd.concat([emp, dept])

    ID     Name  Dept_ID  DEPT_NAME
0  101    Kiran      1.0        NaN
1  102       Om      2.0        NaN
2  103   Poonam      1.0        NaN
3  104  Anushka      3.0        NaN
4  105   Vikram      2.0        NaN
0    1      NaN      NaN  Developer
1    2      NaN      NaN     Tester
2    3      NaN      NaN         HR
3    4      NaN      NaN      Admin

In [8]:
pd.concat([emp, dept], axis = 1)

    ID     Name  Dept_ID   ID  DEPT_NAME
0  101    Kiran        1  1.0  Developer
1  102       Om        2  2.0     Tester
2  103   Poonam        1  3.0         HR
3  104  Anushka        3  4.0      Admin
4  105   Vikram        2  NaN        NaN

In [9]:
emp.loc[emp['Name'] == 'Vikram', 'Dept_ID'] = 5

In [10]:
emp

    ID     Name  Dept_ID
0  101    Kiran        1
1  102       Om        2
2  103   Poonam        1
3  104  Anushka        3
4  105   Vikram        5

In [11]:
pd.merge(emp, dept, left_on = 'Dept_ID', right_on = 'ID', how = 'inner')

   ID_x     Name  Dept_ID  ID_y  DEPT_NAME
0   101    Kiran        1     1  Developer
1   103   Poonam        1     1  Developer
2   102       Om        2     2     Tester
3   104  Anushka        3     3         HR

In [12]:
pd.merge(emp, dept, left_on = 'Dept_ID', right_on = 'ID', how = 'left')

   ID_x     Name  Dept_ID  ID_y  DEPT_NAME
0   101    Kiran        1   1.0  Developer
1   102       Om        2   2.0     Tester
2   103   Poonam        1   1.0  Developer
3   104  Anushka        3   3.0         HR
4   105   Vikram        5   NaN        NaN

In [13]:
pd.merge(emp, dept, left_on = 'Dept_ID' , right_on = 'ID' , how = 'right')

    ID_x     Name  Dept_ID  ID_y  DEPT_NAME
0  101.0    Kiran      1.0     1  Developer
1  103.0   Poonam      1.0     1  Developer
2  102.0       Om      2.0     2     Tester
3  104.0  Anushka      3.0     3         HR
4    NaN      NaN      NaN     4      Admin

In [14]:
pd.merge(emp, dept, left_on = 'Dept_ID' , right_on = 'ID' , how = 'outer')

    ID_x     Name  Dept_ID  ID_y  DEPT_NAME
0  101.0    Kiran      1.0   1.0  Developer
1  103.0   Poonam      1.0   1.0  Developer
2  102.0       Om      2.0   2.0     Tester
3  104.0  Anushka      3.0   3.0         HR
4  105.0   Vikram      5.0   NaN        NaN
5    NaN      NaN      NaN   4.0      Admin