#### Intro
1. Pandas dataframe is two dimensional
2. Size mutable
3. Heterogeneous tabular data structure
4. Labeeled axes(rows and columns)

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([[101,'Poonam','Data Scientist'],[102,'Rakhi','Data Analyst'],[103,'Jagruti','Developer']])
df

     0        1               2
0  101   Poonam  Data Scientist
1  102    Rakhi    Data Analyst
2  103  Jagruti       Developer

In [3]:
df = pd.DataFrame([[101,'Poonam','Data Scientist'],[102,'Rakhi','Data Analyst'],[103,'Jagruti','Developer']], columns = ["ID","NAME","DEPT"])
df

    ID     NAME            DEPT
0  101   Poonam  Data Scientist
1  102    Rakhi    Data Analyst
2  103  Jagruti       Developer

In [4]:
df.index = df['ID']
df

      ID     NAME            DEPT
ID
101  101   Poonam  Data Scientist
102  102    Rakhi    Data Analyst
103  103  Jagruti       Developer

In [5]:
df['ID']

ID
101    101
102    102
103    103
Name: ID, dtype: int64

In [6]:
df['NAME']

ID
101     Poonam
102      Rakhi
103    Jagruti
Name: NAME, dtype: object

In [7]:
ids = [101, 102, 103, 104, 105]
names = ["Poonam", "Rakhi", "Jagruti", "Harshal", "Ayush"]
sal = [30000, 40000, 50000, 60000, 70000]
dept = ["AI Engineer", "Data Scienist", "Software Developer", "Data Scientist", "Gen AI Engineer"]

df2 = pd.DataFrame({"ID" : ids, "NAME" : names, "SALARY" : sal, "DEPT" : dept})
df2

    ID     NAME  SALARY                DEPT
0  101   Poonam   30000         AI Engineer
1  102    Rakhi   40000       Data Scienist
2  103  Jagruti   50000  Software Developer
3  104  Harshal   60000      Data Scientist
4  105    Ayush   70000     Gen AI Engineer

In [8]:
df

      ID     NAME            DEPT
ID
101  101   Poonam  Data Scientist
102  102    Rakhi    Data Analyst
103  103  Jagruti       Developer

In [9]:
df.index = df["NAME"]
df

          ID     NAME            DEPT
NAME
Poonam   101   Poonam  Data Scientist
Rakhi    102    Rakhi    Data Analyst
Jagruti  103  Jagruti       Developer

In [10]:
df.index = ['a','b','c']
df

    ID     NAME            DEPT
a  101   Poonam  Data Scientist
b  102    Rakhi    Data Analyst
c  103  Jagruti       Developer

In [11]:
df2

    ID     NAME  SALARY                DEPT
0  101   Poonam   30000         AI Engineer
1  102    Rakhi   40000       Data Scienist
2  103  Jagruti   50000  Software Developer
3  104  Harshal   60000      Data Scientist
4  105    Ayush   70000     Gen AI Engineer

In [12]:
df2.head()

    ID     NAME  SALARY                DEPT
0  101   Poonam   30000         AI Engineer
1  102    Rakhi   40000       Data Scienist
2  103  Jagruti   50000  Software Developer
3  104  Harshal   60000      Data Scientist
4  105    Ayush   70000     Gen AI Engineer

In [13]:
df2.tail()

    ID     NAME  SALARY                DEPT
0  101   Poonam   30000         AI Engineer
1  102    Rakhi   40000       Data Scienist
2  103  Jagruti   50000  Software Developer
3  104  Harshal   60000      Data Scientist
4  105    Ayush   70000     Gen AI Engineer

In [14]:
df2['SALARY'].mean()

50000.0

In [15]:
df2['SALARY'].max()

70000

In [16]:
df2['SALARY'].min()

30000

In [17]:
df2.max()

ID                       105
NAME                   Rakhi
SALARY                 70000
DEPT      Software Developer
dtype: object

In [18]:
df2['DEPT'].unique()

array(['AI Engineer', 'Data Scienist', 'Software Developer',
       'Data Scientist', 'Gen AI Engineer'], dtype=object)

In [19]:
df2['DEPT'].value_counts()

DEPT
AI Engineer           1
Data Scienist         1
Software Developer    1
Data Scientist        1
Gen AI Engineer       1
Name: count, dtype: int64

In [20]:
df2['DEPT'].nunique()    # Gives count of unique values

5

In [21]:
df2['ADDRESS'] = ['Pune', 'Nashik', 'Mumbai', 'Thane', 'Deola']
df2

    ID     NAME  SALARY                DEPT ADDRESS
0  101   Poonam   30000         AI Engineer    Pune
1  102    Rakhi   40000       Data Scienist  Nashik
2  103  Jagruti   50000  Software Developer  Mumbai
3  104  Harshal   60000      Data Scientist   Thane
4  105    Ayush   70000     Gen AI Engineer   Deola

In [22]:
df2['NAME'] = ['Pune', 'Nashik', 'Mumbai', 'Thane', 'Deola']
df2

    ID    NAME  SALARY                DEPT ADDRESS
0  101    Pune   30000         AI Engineer    Pune
1  102  Nashik   40000       Data Scienist  Nashik
2  103  Mumbai   50000  Software Developer  Mumbai
3  104   Thane   60000      Data Scientist   Thane
4  105   Deola   70000     Gen AI Engineer   Deola

In [23]:
df2['NAME'] = ["Poonam", "Rakhi", "Jagruti", "Harshal", "Ayush"]
df2

    ID     NAME  SALARY                DEPT ADDRESS
0  101   Poonam   30000         AI Engineer    Pune
1  102    Rakhi   40000       Data Scienist  Nashik
2  103  Jagruti   50000  Software Developer  Mumbai
3  104  Harshal   60000      Data Scientist   Thane
4  105    Ayush   70000     Gen AI Engineer   Deola

In [24]:
df2.insert(2, value = [23, 20, 20, 18, 16] , column = 'AGE')
df2

    ID     NAME  AGE  SALARY                DEPT ADDRESS
0  101   Poonam   23   30000         AI Engineer    Pune
1  102    Rakhi   20   40000       Data Scienist  Nashik
2  103  Jagruti   20   50000  Software Developer  Mumbai
3  104  Harshal   18   60000      Data Scientist   Thane
4  105    Ayush   16   70000     Gen AI Engineer   Deola

In [25]:
df2.drop(2)

    ID     NAME  AGE  SALARY             DEPT ADDRESS
0  101   Poonam   23   30000      AI Engineer    Pune
1  102    Rakhi   20   40000    Data Scienist  Nashik
3  104  Harshal   18   60000   Data Scientist   Thane
4  105    Ayush   16   70000  Gen AI Engineer   Deola

In [26]:
df2

    ID     NAME  AGE  SALARY                DEPT ADDRESS
0  101   Poonam   23   30000         AI Engineer    Pune
1  102    Rakhi   20   40000       Data Scienist  Nashik
2  103  Jagruti   20   50000  Software Developer  Mumbai
3  104  Harshal   18   60000      Data Scientist   Thane
4  105    Ayush   16   70000     Gen AI Engineer   Deola

In [27]:
df2 = df2.drop(2)

In [28]:
df2

    ID     NAME  AGE  SALARY             DEPT ADDRESS
0  101   Poonam   23   30000      AI Engineer    Pune
1  102    Rakhi   20   40000    Data Scienist  Nashik
3  104  Harshal   18   60000   Data Scientist   Thane
4  105    Ayush   16   70000  Gen AI Engineer   Deola

In [29]:
df2.drop(4, inplace = True)

In [30]:
df2

    ID     NAME  AGE  SALARY            DEPT ADDRESS
0  101   Poonam   23   30000     AI Engineer    Pune
1  102    Rakhi   20   40000   Data Scienist  Nashik
3  104  Harshal   18   60000  Data Scientist   Thane

In [31]:
df2.drop('AGE' , axis = 1)

    ID     NAME  SALARY            DEPT ADDRESS
0  101   Poonam   30000     AI Engineer    Pune
1  102    Rakhi   40000   Data Scienist  Nashik
3  104  Harshal   60000  Data Scientist   Thane

In [32]:
df2

    ID     NAME  AGE  SALARY            DEPT ADDRESS
0  101   Poonam   23   30000     AI Engineer    Pune
1  102    Rakhi   20   40000   Data Scienist  Nashik
3  104  Harshal   18   60000  Data Scientist   Thane

In [33]:
df2 = df2.drop('AGE' , axis = 1)

In [34]:
df2

    ID     NAME  SALARY            DEPT ADDRESS
0  101   Poonam   30000     AI Engineer    Pune
1  102    Rakhi   40000   Data Scienist  Nashik
3  104  Harshal   60000  Data Scientist   Thane

In [35]:
df2.drop('ADDRESS' , axis = 1 , inplace = True)

In [36]:
df2

    ID     NAME  SALARY            DEPT
0  101   Poonam   30000     AI Engineer
1  102    Rakhi   40000   Data Scienist
3  104  Harshal   60000  Data Scientist

In [37]:
df2

    ID     NAME  SALARY            DEPT
0  101   Poonam   30000     AI Engineer
1  102    Rakhi   40000   Data Scienist
3  104  Harshal   60000  Data Scientist

In [39]:
df2.loc[1]

ID                  102
NAME              Rakhi
SALARY            40000
DEPT      Data Scienist
Name: 1, dtype: object

In [42]:
df2.index=df2['ID']
df2

      ID     NAME  SALARY            DEPT
ID
101  101   Poonam   30000     AI Engineer
102  102    Rakhi   40000   Data Scienist
104  104  Harshal   60000  Data Scientist

In [43]:
df2.loc[102]

ID                  102
NAME              Rakhi
SALARY            40000
DEPT      Data Scienist
Name: 102, dtype: object

In [44]:
df2.iloc[1]

ID                  102
NAME              Rakhi
SALARY            40000
DEPT      Data Scienist
Name: 102, dtype: object

In [45]:
df2.loc[[101,102,104]]

      ID     NAME  SALARY            DEPT
ID
101  101   Poonam   30000     AI Engineer
102  102    Rakhi   40000   Data Scienist
104  104  Harshal   60000  Data Scientist

In [46]:
df2.loc[df2['NAME'] == 'Rakhi' , 'SALARY'] = 80000

In [47]:
df2

      ID     NAME  SALARY            DEPT
ID
101  101   Poonam   30000     AI Engineer
102  102    Rakhi   80000   Data Scienist
104  104  Harshal   60000  Data Scientist

In [48]:
df2.reset_index(drop = True)

    ID     NAME  SALARY            DEPT
0  101   Poonam   30000     AI Engineer
1  102    Rakhi   80000   Data Scienist
2  104  Harshal   60000  Data Scientist

In [49]:
df2.set_index('ID')

        NAME  SALARY            DEPT
ID
101   Poonam   30000     AI Engineer
102    Rakhi   80000   Data Scienist
104  Harshal   60000  Data Scientist