In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/User/Desktop/Poonam FBS/Data Analysis/Datasets/student_10.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [6]:
df.describe()

        Student ID      Class  Study hrs  Percentage
count     7.000000  10.000000   8.000000    7.000000
mean   1006.000000  11.100000   4.375000   72.142857
std       3.464102   0.875595   3.020761   15.236235
min    1001.000000  10.000000   0.000000   50.000000
25%    1003.500000  10.250000   2.750000   60.000000
50%    1007.000000  11.000000   4.000000   80.000000
75%    1008.500000  12.000000   6.000000   82.500000
max    1010.000000  12.000000  10.000000   90.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes

### Handling Missing Values

In [8]:
df.isnull()

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [10]:
df[df.isnull().any(axis=1)]

         Date  Student ID  Class  Study hrs  Percentage
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0

In [20]:
df.dropna(inplace = True)

In [21]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [22]:
df = pd.read_csv("C:/Users/User/Desktop/Poonam FBS/Data Analysis/Datasets/student_10.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [23]:
df.fillna(value = 0)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         0.0     10        3.0        60.0
3  06-07-2021         0.0     11        0.0         0.0
4  07-07-2021      1005.0     11        4.0         0.0
5  08-07-2021         0.0     11       10.0         0.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        0.0        90.0
8  11-07-2021      1009.0     12        0.0        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [24]:
df['Study hrs'] = df['Study hrs'].fillna(df['Study hrs'].mean())

In [25]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021         NaN     10      3.000        60.0
3  06-07-2021         NaN     11      0.000         NaN
4  07-07-2021      1005.0     11      4.000         NaN
5  08-07-2021         NaN     11     10.000         NaN
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [26]:
df.isnull().sum()

Date          0
Student ID    3
Class         0
Study hrs     0
Percentage    3
dtype: int64

In [27]:
df.bfill()    # backward fill

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021      1005.0     10      3.000        60.0
3  06-07-2021      1005.0     11      0.000        80.0
4  07-07-2021      1005.0     11      4.000        80.0
5  08-07-2021      1007.0     11     10.000        80.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [28]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021         NaN     10      3.000        60.0
3  06-07-2021         NaN     11      0.000         NaN
4  07-07-2021      1005.0     11      4.000         NaN
5  08-07-2021         NaN     11     10.000         NaN
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [29]:
df.ffill()        # forward fill

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021      1002.0     10      3.000        60.0
3  06-07-2021      1002.0     11      0.000        60.0
4  07-07-2021      1005.0     11      4.000        60.0
5  08-07-2021      1005.0     11     10.000        60.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [30]:
df.interpolate()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021      1003.0     10      3.000        60.0
3  06-07-2021      1004.0     11      0.000        65.0
4  07-07-2021      1005.0     11      4.000        70.0
5  08-07-2021      1006.0     11     10.000        75.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [31]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021         NaN     10      3.000        60.0
3  06-07-2021         NaN     11      0.000         NaN
4  07-07-2021      1005.0     11      4.000         NaN
5  08-07-2021         NaN     11     10.000         NaN
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

### Group by